# Generated by Django 2.2.4 on 2021-01-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='is_done',
            field=models.BooleanField(default=True),
        ),
    ]
